services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: betalent-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - betalent-network

  db:
    image: mysql:8.0
    container_name: betalent-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: betalent_payments
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - betalent-network

  nginx:
    image: nginx:alpine
    container_name: betalent-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/html
    depends_on:
      - app
    networks:
      - betalent-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: betalent-frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0 # ⬅️ Adicione esta linha
    networks:
      - betalent-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: betalent-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - betalent-network

  gateway1:
    image: matheusprotzen/gateways-mock
    container_name: betalent-gateway1
    ports:
      - "3001:3001"
    networks:
      - betalent-network

  gateway2:
    image: matheusprotzen/gateways-mock
    container_name: betalent-gateway2
    ports:
      - "3002:3002"
    networks:
      - betalent-network

volumes:
  dbdata:

networks:
  betalent-network:
    driver: bridge
